index.html

Updated the implementations section to have more consistency.
Aimed to have each section just talk about what is implemented, and link to where users can get the software. Updated links for consistency. Also rearranged a bit, so users coming to the site see software they recognize first.

Implementations updates

---

spec/annexes/background.adoc
spec/annexes/normref.adoc

Updating reference 18

---

spec/annexes/background.adoc

cleaning up merge, adding GH issue URLs

---

index.html

Added NGA GeoPackage SDKs and Apps to implementations to index.html.

Added NGA GeoPackage SDKs and Apps to implementations

---

spec/1_base.adoc

srs.id -> srs_id
Also fix formatting to make it consistent.

Fix typo in gpkg_contents table description

---

spec/annexes/ddl.adoc

If we have a breaking change for this table(#130), lets finish the job.

Downcase description in gpkg_data_column_constraints

---

spec/2a_features.adoc

removed extraneous word

---

index.html

* Updated the National Geospatial-Intelligence Agency implementation section
* NGA GeoPackage Libraries URL
* NGA GeoPackage iOS URLS

NGA Implementation Update including iOS links

---

index.html

updating Esri blurb

---

spec/2c_schema.adoc
spec/annexes/normref.adoc

defining GLOB

---

LICENSE.md
README.md
process.md
spec/0_introduction.adoc
spec/1_base.adoc
spec/2a_features.adoc
spec/2b_tiles.adoc
spec/2c_schema.adoc
spec/2e_extensions-mechanism.adoc
spec/4_security.adoc
spec/annexes/background.adoc
spec/annexes/normref.adoc
spec/index.adoc

Administrative edits

---

spec/annexes/extension_geometry_encoding.adoc
spec/annexes/extension_geometry_srsid_triggers.adoc
spec/annexes/extension_geometry_type_triggers.adoc
spec/annexes/extension_geometry_types.adoc
spec/annexes/extension_spatialindex.adoc
spec/annexes/extension_tiles_webp.adoc
spec/annexes/extension_zoom_other_intervals.adoc
spec/annexes/extensions.adoc
spec/index.adoc

moving all extensions under the same annex

---

spec/annexes/ats.adoc
spec/annexes/extension_crs_wkt.adoc
spec/annexes/extension_geometry_encoding.adoc
spec/annexes/extension_geometry_srsid_triggers.adoc
spec/annexes/extension_geometry_type_triggers.adoc
spec/annexes/extension_geometry_types.adoc
spec/annexes/extension_metadata.adoc
spec/annexes/extension_schema.adoc
spec/annexes/extension_spatialindex.adoc
spec/annexes/extension_tiles_webp.adoc
spec/annexes/extension_zoom_other_intervals.adoc

fixing ATS

---

spec/annexes/background.adoc

change log

---

spec/1_base.adoc
spec/annexes/extension_schema.adoc

Making "name" unique

---

spec/1_base.adoc
spec/annexes/background.adoc

Bump version number

---

spec/annexes/extension_crs_wkt.adoc

A new approach for implementing the extension F.10

---

spec/1_base.adoc
spec/annexes/background.adoc
spec/corrigendum_text.adoc
spec/index.adoc

Version Number, corrigendum text

---

index.html

Adding National Geospatial-Intelligence Agency GeoPackage JavaScript library to implementations

NGA GeoPackage JavaScript library

---

spec/annexes/background.adoc

Proposal from WMTS standard
This commit fixes #213

Proposition for Tile Pyramid

---

spec/2b_tiles.adoc
spec/annexes/extension_crs_wkt.adoc
spec/annexes/extension_schema.adoc

This includes fixes for issue #231.
It also includes fixes for the incorrect column name definition_12_163 in the WKT Extension. It should be definition_12_063,

Fixes for issue 231 and Fixes for incorrect WKT document number in WKT extension.

---

spec/2e_extensions-mechanism.adoc

clarifying role of definition column

---

spec/0_introduction.adoc
spec/1_base.adoc
spec/2f_attributes.adoc
spec/annexes/ats.adoc
spec/annexes/ddl.adoc
spec/index.adoc

adding attributes section #221

---

spec/annexes/ddl.adoc
spec/annexes/extension_crs_wkt.adoc
spec/annexes/extension_metadata.adoc
spec/annexes/extension_schema.adoc
spec/annexes/extension_tiled_gridded_elevation_data_png.adoc
spec/annexes/extension_tiled_gridded_elevation_data_tiff.adoc

scrubbing extraneous break boxes in front of each DDL table

---

spec/annexes/extension_schema.adoc

min/max_is_inclusive #260

---

spec/1_base.adoc

rewriting requirement 2 to use GPKG application_id + user_version

---

spec/annexes/ats.adoc

removing incorrect WHERE clause #279

---

spec/annexes/ats.adoc
spec/annexes/ddl.adoc

adding NOT NULL to DDL

---

spec/annexes/ats.adoc

fixing #285

---

spec/annexes/ats.adoc

fixing #288

---

spec/2b_tiles.adoc
spec/annexes/ats.adoc

removing 'tiles' stipulation from REQ39/43

---

spec/annexes/ats.adoc

various typographical issues

---

spec/1_base.adoc
spec/annexes/ats.adoc

Removing Requirement 9

---

spec/annexes/ats.adoc

removing test since there are multiple valid ways to specify this

---

spec/annexes/extension_tiled_gridded_elevation_data.adoc

Adding two requirements to indicate that tables must be populated

---

spec/annexes/extension_tiled_gridded_elevation_data.adoc

Adding recommendation

---

spec/annexes/extension_tiled_gridded_elevation_data.adoc

localized misnumbering

---

spec/annexes/extension_tiled_gridded_elevation_data.adoc

specifying default of pixel-is-area

---

spec/annexes/ats.adoc

removing unneeded test

---

spec/2f_attributes.adoc

better attributes defintion from @kryden

---

spec/1_base.adoc
spec/2a_features.adoc
spec/annexes/ats.adoc
spec/annexes/extension_geometry_types.adoc

R31 and Annex F.1

---

spec/annexes/ats.adoc
spec/annexes/extension_tiled_gridded_elevation_data.adoc
spec/annexes/extension_tiles_webp.adoc

Reviewing WebP Extension

---

spec/2b_tiles.adoc

rewriting tiles introduction to highlight its link to WMTS

---

spec/annexes/extension_tiled_gridded_elevation_data.adoc

R143 got misplaced

---

spec/annexes/normref.adoc

Updating reference for ISO 19115

---

README.md
spec/0_introduction.adoc
spec/annexes/extension_tiled_gridded_elevation_data.adoc

Flagging F.11, adding attributes

---

spec/annexes/extension_crs_wkt.adoc

#363 adding R145 for CRS WKT extension

---

spec/1_base.adoc
spec/2b_tiles.adoc

#366 clarifying tile matrix set extents, adding R144

---

spec/2b_tiles.adoc

removing improper defaults #358

---

spec/annexes/extension_spatialindex.adoc

This is based on feedback from @rcasscslt

minor corrections to R76 and its ATS

---

spec/2e_extensions-mechanism.adoc
spec/annexes/ats.adoc
spec/annexes/background.adoc

adding explanatory text for non-case-sensitivity of table names

---

spec/4_security.adoc

and respond accordingly

---

spec/1_base.adoc
spec/annexes/endnotes.adoc

Adding reference to database limits

---

spec/annexes/metadataexample.adoc

fixing DDL in metadata example

---

spec/annexes/ats.adoc
spec/annexes/extension_geometry_types.adoc

updating incorrect table references to Annex G

---

spec/2a_features.adoc
spec/2b_tiles.adoc
spec/2e_extensions-mechanism.adoc
spec/annexes/endnotes.adoc
spec/annexes/extension_geometry_types.adoc
spec/annexes/extension_metadata.adoc
spec/annexes/extension_schema.adoc

clarifications on views #395

---

spec/annexes/extension_spatialindex.adoc

Based on https://twitter.com/cartocalypse/status/934037511692804096

text cleanup

---

spec/2a_features.adoc
spec/annexes/extension_geometry_encoding.adoc
spec/annexes/extension_geometry_srsid_triggers.adoc
spec/annexes/extension_geometry_type_triggers.adoc

I402 Clarifying GeoPackageBinary 'X' bit

---

spec/1_base.adoc

This swallows #410, but I chose a slightly different wording than what was proposed there.

Contents table can have attributes too

---

spec/annexes/extension_spatialindex.adoc

#414 removing erroneous part of trigger

---

spec/2b_tiles.adoc

revising wording

---

spec/annexes/background.adoc
spec/annexes/extension_crs_wkt.adoc
spec/annexes/extension_metadata.adoc
spec/annexes/extension_schema.adoc
spec/annexes/extension_spatialindex.adoc

Adding required gpkg_extensions columns

---

spec/annexes/background.adoc
spec/annexes/extension_geometry_types.adoc
spec/annexes/extension_zoom_other_intervals.adoc

correcting ATS references

---

spec/1_base.adoc
spec/2a_features.adoc
spec/2b_tiles.adoc
spec/annexes/ats.adoc

#444 enforce match between srs_ids

---

spec/annexes/ats.adoc

Tweaks to tests for #444

---

spec/2a_features.adoc
spec/annexes/ats.adoc

eliminate use of "assignable" #445

---

spec/0_introduction.adoc
spec/1_base.adoc
spec/2a_features.adoc
spec/2b_tiles.adoc
spec/2e_extensions-mechanism.adoc
spec/2f_attributes.adoc
spec/annexes/background.adoc
spec/annexes/extension_crs_wkt.adoc
spec/annexes/extension_metadata.adoc
spec/annexes/extension_schema.adoc
spec/annexes/geometrytypes.adoc

updating table references #455

---

spec/0_introduction.adoc
spec/1_base.adoc
spec/2a_features.adoc
spec/2b_tiles.adoc
spec/2e_extensions-mechanism.adoc
spec/2f_attributes.adoc
spec/annexes/background.adoc
spec/annexes/extension_crs_wkt.adoc
spec/annexes/extension_metadata.adoc
spec/annexes/extension_schema.adoc
spec/annexes/geometrytypes.adoc

Reverts opengeospatial/geopackage#456

Revert "updating table references #455"

---

spec/1_base.adoc

adding note encouraging use of safe identifier names

---

spec/2f_attributes.adoc
spec/annexes/extension_schema.adoc

#453 relaxing R104 to allow use with extensions

---

spec/0_introduction.adoc
spec/1_base.adoc
spec/2a_features.adoc
spec/2b_tiles.adoc
spec/2e_extensions-mechanism.adoc
spec/2f_attributes.adoc
spec/annexes/background.adoc
spec/annexes/extension_crs_wkt.adoc
spec/annexes/extension_metadata.adoc
spec/annexes/extension_schema.adoc
spec/annexes/geometrytypes.adoc

This reverts commit 2fd987b629a6779165c95f2ece71d81e64050d4c in a second attempt to fix #455

Revert "Revert "updating table references #455""

---

spec/2b_tiles.adoc

adding warning

---

spec/2a_features.adoc
spec/2b_tiles.adoc
spec/2f_attributes.adoc
spec/annexes/ats.adoc

Adding R150, R151, updating R54 to support views #446

---

spec/annexes/extension_spatialindex.adoc

Removed test for Req.78 and inserted Note on index practice

---

spec/annexes/extension_schema.adoc

modifying constraint to be for table_name+column_name #487

---

spec/2a_features.adoc

slight wording change

---

spec/annexes/normref.adoc

changing normative reference for WKT2

---

spec/annexes/extension_crs_wkt.adoc

Change gpkg_schema to gpkg_crs_wkt in test method. See requirement 145.
Fixes #509.

Change gpkg_schema to gpkg_crs_wkt

---

spec/2a_features.adoc
spec/annexes/ats.adoc

adding SHOULD for empty geometry flag

---

spec/annexes/extension_schema.adoc

Fixed to gpkg_data_columns Data Columns Table Definition unique constraint to match #492 (formatting matches http://www.geopackage.org/spec/index.html#tiles_user_tables)

gpkg_data_columns unique constraint

---

spec/1_base.adoc
spec/annexes/ats.adoc
spec/annexes/background.adoc
spec/index.adoc

perfunctory changes for v1.3.0

---

spec/2a_features.adoc
spec/2b_tiles.adoc
spec/2f_attributes.adoc
spec/annexes/ddl.adoc
spec/annexes/endnotes.adoc
spec/annexes/extension_metadata.adoc
spec/annexes/metadataexample.adoc
spec/annexes/triggers.adoc

Closes #498
Closes #517
Closes #524 
Closes #525

Multiple clarifications

---

spec/annexes/background.adoc
spec/annexes/extension_spatialindex.adoc

Closes #532
Closes #529 
Closes #535

Updates to Spatial Index Extension

---

spec/1_base.adoc

clarifying role of srs_id as different from organization_coordsys_id

---

spec/2a_features.adoc
spec/2b_tiles.adoc
spec/2f_attributes.adoc
spec/annexes/endnotes.adoc

rewriting R29, R150, R54, R119, R151, adding R153 to clarify views

---

spec/annexes/normref.adoc

updating normative references with updated information

---

spec/2a_features.adoc
spec/annexes/endnotes.adoc

clarifying WKB axis order

---

spec/annexes/extension_crs_wkt.adoc
spec/annexes/normref.adoc

@kryden is this what you had in mind? This is not clear to me.

clarifying use of 12-063 vs. 18-010

---

spec/1_base.adoc

refining wording in note regarding identifiers

---

spec/2a_features.adoc

minor edit suggested by KR

---

spec/1_base.adoc

fixing media type

---

spec/core/0_introduction.adoc
spec/core/2b_tiles.adoc
spec/core/2e_extensions-mechanism.adoc
spec/core/annexes/background.adoc
spec/core/annexes/metadataexample.adoc
spec/core/index.adoc

SP edits for publication of v 1.3

---

README.md
process.md
spec/2d-gridded-coverage/standard_document.adoc

Perfunctory cleanup to repo itself

---

index.html

reflecting 1.3.0 and other back-end changes

---

spec/core/annexes/ats.adoc

Proposed solution for the ATS part of #570.

Strike through test case for deleted req 17

---

spec/core/annexes/ddl.adoc

cleaned up column name in st_geometry_columns

---

spec/core/1_base.adoc

closes #590
closes #591
closes #558

adding two warnings for REQ5

---

spec/core/1_base.adoc

Update text regarding identifier case

---

spec/conceptual-model/clause_6_informative_text.adoc
spec/core/index.adoc
spec/core/release_notes/1.3.1/clause-4-change-log.adoc
spec/core/release_notes/1.3.1/clause-5-critical.adoc
spec/core/release_notes/1.3.1/clause-6-substantive.adoc

Also an administrative change to the conceptual/logical model

GPKG 1.3.1 perfunctory info

---

spec/core/1_base.adoc
spec/core/2f_attributes.adoc
spec/core/annexes/extension_metadata.adoc
spec/core/release_notes/1.3.1/clause-4-change-log.adoc

adding the "entity type" nomenclature

---

spec/core/index.adoc
spec/core/release_notes/1.3.1/clause-0-preface.adoc
spec/core/release_notes/1.3.1/clause-2-references.adoc
spec/core/release_notes/1.3.1/clause-7-future.adoc
spec/core/release_notes/1.3.1/rn.adoc

SP edits for publication

---

spec/crs_wkt/clause_0_front_material.adoc
spec/crs_wkt/standard_document.adoc

cover page and minor edits for publication of CRS extension

SP for publication

---

ghpages/implementation_guide.adoc
spec/core/annexes/biblio.adoc
spec/core/annexes/extension_spatialindex.adoc
spec/core/release_notes/1.4.0/clause-4-change-log.adoc
spec/core/release_notes/1.4.0/clause-6-substantive.adoc

update RTree Spatial Index triggers

---

spec/core/annexes/extension_spatialindex.adoc

Fix RTree update6 update table name
