opengeospatial/geopackage

- spec/annexes/extension_geometry_type_triggers.adoc
See [libspatialite](https://www.gaia-gis.it/fossil/libspatialite/index) (src/geopackage/gpkg_add_geometry_triggers.c) as of v4.3.0 for an example of an implementer who has added the missing close-parens.
Came across this in the course of implementing Annex M for a closed source project.
> add missing close parens in template sql (Annex M)

- spec/2e_extensions-mechanism.adoc
As written, there are only two cases - the GeoPackage specification, or a Best Practices document. That would exclude something like the Elevation Extension (written as a spec, not a best practices). So make it a bit more general and provide some examples.
> Make extension out-reference document more general.

- spec/1_base.adoc
Due to the version bump done in https://github.com/opengeospatial/geopackage/issues/188
> Update Req2 Foot1 with correct decimal and hexadecimal values for GP11

- spec/2b_tiles.adoc
It's a very minor thing, but I figured I might as well point it out.
I searched the rest of the spec, and found no more instances of ` th ` *(except in the CSS, which is fine of course)*
> Fix typo: "th" --> "the"

- spec/1_base.adoc
reading the spec, a developer would likely take these mins and maxes literally from the spec, which seems to contradict the "Getting Started" guidelines: http://www.geopackage.org/guidance/getting-started.html#gpkg_contents
Syncing up this verbage for the guideline with the spec would clear up confusion.
> more clarity on bounds for tiles

- spec/2f_attributes.adoc
- spec/annexes/extension_schema.adoc
Addresses the rest of #453 by swallowing #458 but goes further in terms of clarifying how the values are to be used. Includes ATS and DDL updates and warnings.
> Clarify use of table_name to refer to contents or extensions

- spec/annexes/extension_schema.adoc
This pull request updates the description of the table_name column in the gpkg_data_columns to be more in line with Requirement 104.
The description for the column table_name in Table 23 states: 'Name of the tiles or feature table', however the description of Requirement 104 states: 'Values of the gpkg_data_columns table table_name column value SHALL reference values in the gpkg_contents table_name column.'. This leads me to believe that any type of table that is in the gpkg_contents table should be allowed in the table_name of the gpkg_data_columns table, including Attributes tables.
The description for the table_name column in Table 23 should be updated to be in line with Requirement 104.
> Data Columns for Attributes Tables

- spec/annexes/ats.adoc
The test covers 1.0, 1.1 and the 1.2+ versions.
Resolves #471
> ATS version check supporting text to be 1.x

- spec/2e_extensions-mechanism.adoc
The "write_only" value (with underscore) was used, whereas "write-only" (with dash) is used every where else.
> Extension: fix typo in text regarding "write-only"

- spec/annexes/extension_geometry_types.adoc
- spec/annexes/extension_metadata.adoc
- spec/annexes/extension_tiles_webp.adoc
* eliminate trigger definition SQL since it is overly restrictive - it prevents us from adding new metadata scopes (this can be handled in the ATS/ETS)
* add new metadata scope value of "style"
* fix some extraneous hyperlinks
closes #495
> correct problems with metadata scopes ISO TB-15

- spec/annexes/extension_metadata.adoc
> clarifying metadata extension

- spec/1_base.adoc
- spec/annexes/background.adoc
- spec/annexes/extension_schema.adoc
This swallows #497.
This eliminates a key value of "unique" in favor of "UK" or "Jointly Unique".
> Use uniqueness keys consistently in "table" tables

- spec/annexes/extension_spatialindex.adoc
The original statement fails in the case where some of the existing
geometries are empty. The error message is:
rtree constraint failed: rtree_Building_geom.(minx<=maxx)
This change modifies the statement so that it only attempts to populate
the rtree with non-empty (or NULL) geometries. This is consistent with
the rtree triggers.
> Fix rtree creation SQL statement

- spec/2a_features.adoc
> clarifying the use of byte order flags

- spec/core/annexes/extension_schema.adoc
The test refered to a non-existent constraint_type column in gpkg_data_columns.
Align with the actual requirements of Req 106.
> Fix ATS extensions/schema/data_columns/constraint_name test case

- spec/core/annexes/extension_metadata.adoc
Errata: "A GeoPackage A GeoPackage MAY contain a table named gpkg_metadata. If present it SHALL be defined per clauses Metadata Table, Table 1, and gpkg_metadata Table Definition SQL."
Corrige: "A GeoPackage MAY contain a table named gpkg_metadata. If present it SHALL be defined per clauses Metadata Table, Table 1, and gpkg_metadata Table Definition SQL."
> Fixe typo in extension_metadata.adoc

- spec/core/annexes/extension_metadata.adoc
The original pull request deleted the abstract test from the document but it is better to use a line-through to indicate that this has occurred.
> switching to strikethrough for #588

- spec/core/annexes/extension_crs_wkt.adoc
> adding an "epoch" column to gpkg_spatial_ref_sys

- spec/core/1_base.adoc
- spec/core/annexes/ats.adoc
- spec/core/annexes/endnotes.adoc
- spec/core/annexes/extension_metadata.adoc
Update the relevant end notes and tests.
Add warning regarding the use of the built-in date and time functions. This is a substantive change.
Closes #648
Encapsulates #649 and #651
> Make DATETIME seconds optional and fractional seconds more flexible

- spec/core/1_base.adoc
- spec/core/annexes/extension_geometry_srsid_triggers.adoc
- spec/core/annexes/extension_geometry_type_triggers.adoc
- spec/core/release_notes/1.4.0/clause-4-change-log.adoc
> adding note regarding PRAGMA user_version

- spec/core/annexes/extension_spatialindex.adoc
- spec/core/release_notes/1.4.0/annex-history.adoc
- spec/core/release_notes/1.4.0/clause-4-change-log.adoc
Follow-up of https://github.com/opengeospatial/geopackage/pull/661 
Swallows https://github.com/opengeospatial/geopackage/pull/663
drop _old_geom_notnull suffix from _update6 trigger and _old_geom_null suffix from _update7 trigger
also: revising summary based on OAB feedback
> Patch R-tree index triggers

- spec/core/1_base.adoc
- spec/core/annexes/biblio.adoc
The document previously available at [http://www.epsg.org/guides/docs/_**G7-1**_.pdf](http://www.epsg.org/guides/docs/G7-1.pdf) (see [c8f4642de502c2eff04a7aaed62d1c6faccdae2b](https://github.com/opengeospatial/geopackage/commit/c8f4642de502c2eff04a7aaed62d1c6faccdae2b#diff-0283a391ff59b99966df611614eee90152b8e5c474bc24d9d41b967929ec5fd9) and #670) is available via https://epsg.org/guidance-notes.html
The direct link is https://drive.tiny.cloud/1/4m326iu12oa8re9cjiadxonharclteqb4mumfxj71zsttwkx/07cead43-4462-436c-8636-5da9531eebfd, but https://epsg.org/guidance-notes.html is a more persistent link, therefore the proposal to use the latter link in the bibliography.
> Update EPSG reference B3
